### ISSUE TITLE
[!] Player items are disappearing

### ISSUE THREAD

**Issue by caiobarnes** [Jikoo/OpenInv#216]
Good evening, developer,

The version of my server is **1.20.4**, and I am using version **4.4.5** of the **OpenInv** plugin. I have a multi-server survival. I use it on server1 and server2. However, when the player switches servers, usually in version 1.21, the items disappear. This is my configuration

```
config-version: 6
settings:
  command:
    open:
      no-args-opens-self: false
    searchcontainer:
      max-radius: 10
  disable-offline-access: false
  disable-saving: false
  locale: en_us
toggles:
  any-chest:
    f08d5d85-947c-48f7-bb9a-7f7aa04ecc21: false
```
