### ISSUE TITLE
/sc command overriding staffchat commands

### ISSUE THREAD

**Issue by TechnicallyCoded** [Jikoo/OpenInv#81]
Could the short form of the command "/sc" (silentcontainer) be removed or toggleable in config since that's a command frequently used by staff chat and this plugin prevents people from running the command.

**Comment by Jikoo** [comment]
You can use Bukkit's [commands.yml](https://bukkit.fandom.com/wiki/Commands.yml) to resolve command conflicts.

```yaml
aliases:
    sc:
    - "staffchat:staffchat $1-"
```
